<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M2p6XgFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M2p6XgF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M2p6XgF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionAnswer' => ['privates', '.errored..service_locator.M2p6XgF.App\\Entity\\QuestionAnswer', NULL, 'Cannot autowire service ".service_locator.M2p6XgF": it references class "App\\Entity\\QuestionAnswer" but no such service exists.'],
        ], [
            'questionAnswer' => 'App\\Entity\\QuestionAnswer',
        ]);
    }
}
