<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KHwR08wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KHwR08w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KHwR08w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored..service_locator.KHwR08w.App\\Entity\\Answer', NULL, 'Cannot autowire service ".service_locator.KHwR08w": it references class "App\\Entity\\Answer" but no such service exists.'],
            'answerRepository' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService', true],
        ], [
            'answer' => 'App\\Entity\\Answer',
            'answerRepository' => 'App\\Repository\\AnswerRepository',
        ]);
    }
}
