<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jykf7yAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jykf7yA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jykf7yA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\UserGameAnswerRepository', 'getUserGameAnswerRepositoryService', true],
            'serializerInterface' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'repo' => 'App\\Repository\\UserGameAnswerRepository',
            'serializerInterface' => '?',
            'validator' => '?',
        ]);
    }
}
