<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LxEH0eqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LxEH0eq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LxEH0eq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'level' => ['privates', '.errored..service_locator.LxEH0eq.App\\Entity\\Level', NULL, 'Cannot autowire service ".service_locator.LxEH0eq": it references class "App\\Entity\\Level" but no such service exists.'],
        ], [
            'level' => 'App\\Entity\\Level',
        ]);
    }
}
