<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z0PbonIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0PbonI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z0PbonI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'game' => ['privates', '.errored..service_locator.z0PbonI.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.z0PbonI": it references class "App\\Entity\\Game" but no such service exists.'],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'game' => 'App\\Entity\\Game',
            'gameRepository' => 'App\\Repository\\GameRepository',
        ]);
    }
}
