<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QwnmcR7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QwnmcR7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QwnmcR7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored..service_locator.QwnmcR7.App\\Entity\\Answer', NULL, 'Cannot autowire service ".service_locator.QwnmcR7": it references class "App\\Entity\\Answer" but no such service exists.'],
        ], [
            'answer' => 'App\\Entity\\Answer',
        ]);
    }
}
