<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DYfXpHZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DYfXpHZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DYfXpHZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'game' => ['privates', '.errored..service_locator.DYfXpHZ.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.DYfXpHZ": it references class "App\\Entity\\Game" but no such service exists.'],
        ], [
            'game' => 'App\\Entity\\Game',
        ]);
    }
}
