<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cc1h1Q8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cc1h1Q8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cc1h1Q8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userGameAnswer' => ['privates', '.errored..service_locator.cc1h1Q8.App\\Entity\\UserGameAnswer', NULL, 'Cannot autowire service ".service_locator.cc1h1Q8": it references class "App\\Entity\\UserGameAnswer" but no such service exists.'],
        ], [
            'userGameAnswer' => 'App\\Entity\\UserGameAnswer',
        ]);
    }
}
