<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YiqeiryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yiqeiry' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yiqeiry'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userGameAnswer' => ['privates', '.errored..service_locator.Yiqeiry.App\\Entity\\UserGameAnswer', NULL, 'Cannot autowire service ".service_locator.Yiqeiry": it references class "App\\Entity\\UserGameAnswer" but no such service exists.'],
            'userGameAnswerRepository' => ['privates', 'App\\Repository\\UserGameAnswerRepository', 'getUserGameAnswerRepositoryService', true],
        ], [
            'userGameAnswer' => 'App\\Entity\\UserGameAnswer',
            'userGameAnswerRepository' => 'App\\Repository\\UserGameAnswerRepository',
        ]);
    }
}
