<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FMKr3GIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fMKr3GI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fMKr3GI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionAnswer' => ['privates', '.errored..service_locator.fMKr3GI.App\\Entity\\QuestionAnswer', NULL, 'Cannot autowire service ".service_locator.fMKr3GI": it references class "App\\Entity\\QuestionAnswer" but no such service exists.'],
            'questionAnswerRepository' => ['privates', 'App\\Repository\\QuestionAnswerRepository', 'getQuestionAnswerRepositoryService', true],
        ], [
            'questionAnswer' => 'App\\Entity\\QuestionAnswer',
            'questionAnswerRepository' => 'App\\Repository\\QuestionAnswerRepository',
        ]);
    }
}
