<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBRmqoyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BBRmqoy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BBRmqoy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'level' => ['privates', '.errored..service_locator.BBRmqoy.App\\Entity\\Level', NULL, 'Cannot autowire service ".service_locator.BBRmqoy": it references class "App\\Entity\\Level" but no such service exists.'],
            'levelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
        ], [
            'level' => 'App\\Entity\\Level',
            'levelRepository' => 'App\\Repository\\LevelRepository',
        ]);
    }
}
