<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnswer2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QwnmcR7.App\Entity\Answer' shared service.
     *
     * @return \App\Entity\Answer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QwnmcR7": it references class "App\\Entity\\Answer" but no such service exists.');
    }
}
