<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLevelControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Back\LevelController' shared autowired service.
     *
     * @return \App\Controller\Back\LevelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Back/LevelController.php';

        $container->services['App\\Controller\\Back\\LevelController'] = $instance = new \App\Controller\Back\LevelController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Back\\LevelController', $container));

        return $instance;
    }
}
