<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLevel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LxEH0eq.App\Entity\Level' shared service.
     *
     * @return \App\Entity\Level
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LxEH0eq": it references class "App\\Entity\\Level" but no such service exists.');
    }
}
