<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionAnswerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M2p6XgF.App\Entity\QuestionAnswer' shared service.
     *
     * @return \App\Entity\QuestionAnswer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M2p6XgF": it references class "App\\Entity\\QuestionAnswer" but no such service exists.');
    }
}
