<?php

namespace ContainerNosjaVT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserGameAnswerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yiqeiry.App\Entity\UserGameAnswer' shared service.
     *
     * @return \App\Entity\UserGameAnswer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Yiqeiry": it references class "App\\Entity\\UserGameAnswer" but no such service exists.');
    }
}
